Update manual.yml

diff --git a/.github/workflows/manual.yml b/.github/workflows/manual.yml
--- a/.github/workflows/manual.yml
+++ b/.github/workflows/manual.yml
@@ -6,7 +6,9 @@ jobs:
     steps:
     - uses: actions/checkout@v2
     - name: Set env
-      run: if [ $? -ne 0 ]; then echo "TF_PLAN_STATE=FAIL" >> $GITHUB_ENV; else  echo "TF_PLAN_STATE=PASS" >> $GITHUB_ENV; fi && echo $GITHUB_ENV | tee RESULT 
+      run: if [ $? -ne 0 ]; then echo "TF_PLAN_STATE=FAIL" >> $GITHUB_ENV; else  echo "TF_PLAN_STATE=PASS" >> $GITHUB_ENV; fi && echo $GITHUB_ENV | tee RESULT
+    - name: get env
+      run: echo $TF_PLAN_STATE
     - name: file creation
       uses: actions/upload-artifact@v2
       with:
