Update manual.yml

diff --git a/.github/workflows/manual.yml b/.github/workflows/manual.yml
--- a/.github/workflows/manual.yml
+++ b/.github/workflows/manual.yml
@@ -6,6 +6,6 @@ jobs:
     steps:
     - uses: actions/checkout@v2
     - name: Set env
-      run: if [ $? -ne 0 ]; then echo "TF_PLAN_STATE=FAIL" >> $GITHUB_ENV; else  echo "TF_PLAN_STATE=PASS" >> $GITHUB_ENV;
+      run: if [ $? -ne 0 ]; then echo "TF_PLAN_STATE=FAIL" >> $GITHUB_ENV; else  echo "TF_PLAN_STATE=PASS" >> $GITHUB_ENV; fi
     - name: Test
       run: echo $TF_PLAN_STATE
